apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: medication-certificate
  namespace: default
spec:
  dnsNames:
    - medication.med-united.health
  secretName: medication-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer

---

kind: Service
apiVersion: v1
metadata:
  name: medication
spec:
  type: ExternalName
  externalName: www.apotheken-umschau.de

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medication
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/preserve-host: 'false'
    nginx.ingress.kubernetes.io/upstream-vhost: "www.apotheken-umschau.de"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - medication.med-united.health
    secretName: medication-tls
  rules:
  - host: medication.med-united.health
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: medication
              port:
                number: 443
